version: "3.8"
   
services:
  lofi_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    command: node index.js
    container_name: lofi_client
    tty: true
    env_file: 
      - .env
    volumes: 
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge